// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: subscribes/contract.proto

package subscribespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AccountId               int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SubscriptionName        string                 `protobuf:"bytes,2,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	SubscriptionTitle       string                 `protobuf:"bytes,3,opt,name=subscription_title,json=subscriptionTitle,proto3" json:"subscription_title,omitempty"`
	SubscriptionPayPerMonth int64                  `protobuf:"varint,4,opt,name=subscription_pay_per_month,json=subscriptionPayPerMonth,proto3" json:"subscription_pay_per_month,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CreateSubRequest) Reset() {
	*x = CreateSubRequest{}
	mi := &file_subscribes_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubRequest) ProtoMessage() {}

func (x *CreateSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubRequest.ProtoReflect.Descriptor instead.
func (*CreateSubRequest) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateSubRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *CreateSubRequest) GetSubscriptionTitle() string {
	if x != nil {
		return x.SubscriptionTitle
	}
	return ""
}

func (x *CreateSubRequest) GetSubscriptionPayPerMonth() int64 {
	if x != nil {
		return x.SubscriptionPayPerMonth
	}
	return 0
}

type CreateSubResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int64                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubResponse) Reset() {
	*x = CreateSubResponse{}
	mi := &file_subscribes_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubResponse) ProtoMessage() {}

func (x *CreateSubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubResponse.ProtoReflect.Descriptor instead.
func (*CreateSubResponse) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubResponse) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type RemoveSubRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SubscriptionId int64                  `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveSubRequest) Reset() {
	*x = RemoveSubRequest{}
	mi := &file_subscribes_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubRequest) ProtoMessage() {}

func (x *RemoveSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubRequest) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSubRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RemoveSubRequest) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type RemoveSubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubResponse) Reset() {
	*x = RemoveSubResponse{}
	mi := &file_subscribes_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubResponse) ProtoMessage() {}

func (x *RemoveSubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubResponse) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveSubResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PutSubRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	AccountId               int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SubscriptionId          int64                  `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	SubscriptionName        string                 `protobuf:"bytes,3,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	SubscriptionTitle       string                 `protobuf:"bytes,4,opt,name=subscription_title,json=subscriptionTitle,proto3" json:"subscription_title,omitempty"`
	SubscriptionPayPerMonth int64                  `protobuf:"varint,5,opt,name=subscription_pay_per_month,json=subscriptionPayPerMonth,proto3" json:"subscription_pay_per_month,omitempty"`
	SubscriptionStatus      int64                  `protobuf:"varint,6,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PutSubRequest) Reset() {
	*x = PutSubRequest{}
	mi := &file_subscribes_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSubRequest) ProtoMessage() {}

func (x *PutSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSubRequest.ProtoReflect.Descriptor instead.
func (*PutSubRequest) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{4}
}

func (x *PutSubRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PutSubRequest) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *PutSubRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *PutSubRequest) GetSubscriptionTitle() string {
	if x != nil {
		return x.SubscriptionTitle
	}
	return ""
}

func (x *PutSubRequest) GetSubscriptionPayPerMonth() int64 {
	if x != nil {
		return x.SubscriptionPayPerMonth
	}
	return 0
}

func (x *PutSubRequest) GetSubscriptionStatus() int64 {
	if x != nil {
		return x.SubscriptionStatus
	}
	return 0
}

type PutSubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSubResponse) Reset() {
	*x = PutSubResponse{}
	mi := &file_subscribes_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSubResponse) ProtoMessage() {}

func (x *PutSubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSubResponse.ProtoReflect.Descriptor instead.
func (*PutSubResponse) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{5}
}

func (x *PutSubResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSubsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubsRequest) Reset() {
	*x = GetSubsRequest{}
	mi := &file_subscribes_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubsRequest) ProtoMessage() {}

func (x *GetSubsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubsRequest.ProtoReflect.Descriptor instead.
func (*GetSubsRequest) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubsRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetSubsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Subscription struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId          int64                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	SubscriptionName        string                 `protobuf:"bytes,2,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	SubscriptionTitle       string                 `protobuf:"bytes,3,opt,name=subscription_title,json=subscriptionTitle,proto3" json:"subscription_title,omitempty"`
	SubscriptionPayPerMonth int64                  `protobuf:"varint,4,opt,name=subscription_pay_per_month,json=subscriptionPayPerMonth,proto3" json:"subscription_pay_per_month,omitempty"`
	SubscriptionStatus      int64                  `protobuf:"varint,5,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	CreatedAtUnix           int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscribes_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription) GetSubscriptionId() int64 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *Subscription) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *Subscription) GetSubscriptionTitle() string {
	if x != nil {
		return x.SubscriptionTitle
	}
	return ""
}

func (x *Subscription) GetSubscriptionPayPerMonth() int64 {
	if x != nil {
		return x.SubscriptionPayPerMonth
	}
	return 0
}

func (x *Subscription) GetSubscriptionStatus() int64 {
	if x != nil {
		return x.SubscriptionStatus
	}
	return 0
}

func (x *Subscription) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetSubsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Subscription        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubsResponse) Reset() {
	*x = GetSubsResponse{}
	mi := &file_subscribes_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubsResponse) ProtoMessage() {}

func (x *GetSubsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscribes_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubsResponse.ProtoReflect.Descriptor instead.
func (*GetSubsResponse) Descriptor() ([]byte, []int) {
	return file_subscribes_contract_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubsResponse) GetItems() []*Subscription {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_subscribes_contract_proto protoreflect.FileDescriptor

const file_subscribes_contract_proto_rawDesc = "" +
	"\n" +
	"\x19subscribes/contract.proto\x12\n" +
	"subscribes\"\xca\x01\n" +
	"\x10CreateSubRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12+\n" +
	"\x11subscription_name\x18\x02 \x01(\tR\x10subscriptionName\x12-\n" +
	"\x12subscription_title\x18\x03 \x01(\tR\x11subscriptionTitle\x12;\n" +
	"\x1asubscription_pay_per_month\x18\x04 \x01(\x03R\x17subscriptionPayPerMonth\"<\n" +
	"\x11CreateSubResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x03R\x0esubscriptionId\"Z\n" +
	"\x10RemoveSubRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x03R\x0esubscriptionId\"-\n" +
	"\x11RemoveSubResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x02\n" +
	"\rPutSubRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\x03R\x0esubscriptionId\x12+\n" +
	"\x11subscription_name\x18\x03 \x01(\tR\x10subscriptionName\x12-\n" +
	"\x12subscription_title\x18\x04 \x01(\tR\x11subscriptionTitle\x12;\n" +
	"\x1asubscription_pay_per_month\x18\x05 \x01(\x03R\x17subscriptionPayPerMonth\x12/\n" +
	"\x13subscription_status\x18\x06 \x01(\x03R\x12subscriptionStatus\"*\n" +
	"\x0ePutSubResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x0eGetSubsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\xa9\x02\n" +
	"\fSubscription\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x03R\x0esubscriptionId\x12+\n" +
	"\x11subscription_name\x18\x02 \x01(\tR\x10subscriptionName\x12-\n" +
	"\x12subscription_title\x18\x03 \x01(\tR\x11subscriptionTitle\x12;\n" +
	"\x1asubscription_pay_per_month\x18\x04 \x01(\x03R\x17subscriptionPayPerMonth\x12/\n" +
	"\x13subscription_status\x18\x05 \x01(\x03R\x12subscriptionStatus\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\"A\n" +
	"\x0fGetSubsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.subscribes.SubscriptionR\x05items2\xac\x02\n" +
	"\x11SubscribesService\x12H\n" +
	"\tCreateSub\x12\x1c.subscribes.CreateSubRequest\x1a\x1d.subscribes.CreateSubResponse\x12H\n" +
	"\tRemoveSub\x12\x1c.subscribes.RemoveSubRequest\x1a\x1d.subscribes.RemoveSubResponse\x12?\n" +
	"\x06PutSub\x12\x19.subscribes.PutSubRequest\x1a\x1a.subscribes.PutSubResponse\x12B\n" +
	"\aGetSubs\x12\x1a.subscribes.GetSubsRequest\x1a\x1b.subscribes.GetSubsResponseB(Z&grpc/contracts/subscribes;subscribespbb\x06proto3"

var (
	file_subscribes_contract_proto_rawDescOnce sync.Once
	file_subscribes_contract_proto_rawDescData []byte
)

func file_subscribes_contract_proto_rawDescGZIP() []byte {
	file_subscribes_contract_proto_rawDescOnce.Do(func() {
		file_subscribes_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscribes_contract_proto_rawDesc), len(file_subscribes_contract_proto_rawDesc)))
	})
	return file_subscribes_contract_proto_rawDescData
}

var file_subscribes_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_subscribes_contract_proto_goTypes = []any{
	(*CreateSubRequest)(nil),  // 0: subscribes.CreateSubRequest
	(*CreateSubResponse)(nil), // 1: subscribes.CreateSubResponse
	(*RemoveSubRequest)(nil),  // 2: subscribes.RemoveSubRequest
	(*RemoveSubResponse)(nil), // 3: subscribes.RemoveSubResponse
	(*PutSubRequest)(nil),     // 4: subscribes.PutSubRequest
	(*PutSubResponse)(nil),    // 5: subscribes.PutSubResponse
	(*GetSubsRequest)(nil),    // 6: subscribes.GetSubsRequest
	(*Subscription)(nil),      // 7: subscribes.Subscription
	(*GetSubsResponse)(nil),   // 8: subscribes.GetSubsResponse
}
var file_subscribes_contract_proto_depIdxs = []int32{
	7, // 0: subscribes.GetSubsResponse.items:type_name -> subscribes.Subscription
	0, // 1: subscribes.SubscribesService.CreateSub:input_type -> subscribes.CreateSubRequest
	2, // 2: subscribes.SubscribesService.RemoveSub:input_type -> subscribes.RemoveSubRequest
	4, // 3: subscribes.SubscribesService.PutSub:input_type -> subscribes.PutSubRequest
	6, // 4: subscribes.SubscribesService.GetSubs:input_type -> subscribes.GetSubsRequest
	1, // 5: subscribes.SubscribesService.CreateSub:output_type -> subscribes.CreateSubResponse
	3, // 6: subscribes.SubscribesService.RemoveSub:output_type -> subscribes.RemoveSubResponse
	5, // 7: subscribes.SubscribesService.PutSub:output_type -> subscribes.PutSubResponse
	8, // 8: subscribes.SubscribesService.GetSubs:output_type -> subscribes.GetSubsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscribes_contract_proto_init() }
func file_subscribes_contract_proto_init() {
	if File_subscribes_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscribes_contract_proto_rawDesc), len(file_subscribes_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscribes_contract_proto_goTypes,
		DependencyIndexes: file_subscribes_contract_proto_depIdxs,
		MessageInfos:      file_subscribes_contract_proto_msgTypes,
	}.Build()
	File_subscribes_contract_proto = out.File
	file_subscribes_contract_proto_goTypes = nil
	file_subscribes_contract_proto_depIdxs = nil
}
