// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: subscribes/contract.proto

package subscribespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscribesService_CreateSub_FullMethodName = "/subscribes.SubscribesService/CreateSub"
	SubscribesService_RemoveSub_FullMethodName = "/subscribes.SubscribesService/RemoveSub"
	SubscribesService_PutSub_FullMethodName    = "/subscribes.SubscribesService/PutSub"
	SubscribesService_GetSubs_FullMethodName   = "/subscribes.SubscribesService/GetSubs"
)

// SubscribesServiceClient is the client API for SubscribesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscribesServiceClient interface {
	CreateSub(ctx context.Context, in *CreateSubRequest, opts ...grpc.CallOption) (*CreateSubResponse, error)
	RemoveSub(ctx context.Context, in *RemoveSubRequest, opts ...grpc.CallOption) (*RemoveSubResponse, error)
	PutSub(ctx context.Context, in *PutSubRequest, opts ...grpc.CallOption) (*PutSubResponse, error)
	GetSubs(ctx context.Context, in *GetSubsRequest, opts ...grpc.CallOption) (*GetSubsResponse, error)
}

type subscribesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscribesServiceClient(cc grpc.ClientConnInterface) SubscribesServiceClient {
	return &subscribesServiceClient{cc}
}

func (c *subscribesServiceClient) CreateSub(ctx context.Context, in *CreateSubRequest, opts ...grpc.CallOption) (*CreateSubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubResponse)
	err := c.cc.Invoke(ctx, SubscribesService_CreateSub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribesServiceClient) RemoveSub(ctx context.Context, in *RemoveSubRequest, opts ...grpc.CallOption) (*RemoveSubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSubResponse)
	err := c.cc.Invoke(ctx, SubscribesService_RemoveSub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribesServiceClient) PutSub(ctx context.Context, in *PutSubRequest, opts ...grpc.CallOption) (*PutSubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutSubResponse)
	err := c.cc.Invoke(ctx, SubscribesService_PutSub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribesServiceClient) GetSubs(ctx context.Context, in *GetSubsRequest, opts ...grpc.CallOption) (*GetSubsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubsResponse)
	err := c.cc.Invoke(ctx, SubscribesService_GetSubs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscribesServiceServer is the server API for SubscribesService service.
// All implementations must embed UnimplementedSubscribesServiceServer
// for forward compatibility.
type SubscribesServiceServer interface {
	CreateSub(context.Context, *CreateSubRequest) (*CreateSubResponse, error)
	RemoveSub(context.Context, *RemoveSubRequest) (*RemoveSubResponse, error)
	PutSub(context.Context, *PutSubRequest) (*PutSubResponse, error)
	GetSubs(context.Context, *GetSubsRequest) (*GetSubsResponse, error)
	mustEmbedUnimplementedSubscribesServiceServer()
}

// UnimplementedSubscribesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscribesServiceServer struct{}

func (UnimplementedSubscribesServiceServer) CreateSub(context.Context, *CreateSubRequest) (*CreateSubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSub not implemented")
}
func (UnimplementedSubscribesServiceServer) RemoveSub(context.Context, *RemoveSubRequest) (*RemoveSubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSub not implemented")
}
func (UnimplementedSubscribesServiceServer) PutSub(context.Context, *PutSubRequest) (*PutSubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutSub not implemented")
}
func (UnimplementedSubscribesServiceServer) GetSubs(context.Context, *GetSubsRequest) (*GetSubsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubs not implemented")
}
func (UnimplementedSubscribesServiceServer) mustEmbedUnimplementedSubscribesServiceServer() {}
func (UnimplementedSubscribesServiceServer) testEmbeddedByValue()                           {}

// UnsafeSubscribesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscribesServiceServer will
// result in compilation errors.
type UnsafeSubscribesServiceServer interface {
	mustEmbedUnimplementedSubscribesServiceServer()
}

func RegisterSubscribesServiceServer(s grpc.ServiceRegistrar, srv SubscribesServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscribesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscribesService_ServiceDesc, srv)
}

func _SubscribesService_CreateSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribesServiceServer).CreateSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscribesService_CreateSub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribesServiceServer).CreateSub(ctx, req.(*CreateSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribesService_RemoveSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribesServiceServer).RemoveSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscribesService_RemoveSub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribesServiceServer).RemoveSub(ctx, req.(*RemoveSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribesService_PutSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribesServiceServer).PutSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscribesService_PutSub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribesServiceServer).PutSub(ctx, req.(*PutSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribesService_GetSubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribesServiceServer).GetSubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscribesService_GetSubs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribesServiceServer).GetSubs(ctx, req.(*GetSubsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscribesService_ServiceDesc is the grpc.ServiceDesc for SubscribesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscribesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscribes.SubscribesService",
	HandlerType: (*SubscribesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSub",
			Handler:    _SubscribesService_CreateSub_Handler,
		},
		{
			MethodName: "RemoveSub",
			Handler:    _SubscribesService_RemoveSub_Handler,
		},
		{
			MethodName: "PutSub",
			Handler:    _SubscribesService_PutSub_Handler,
		},
		{
			MethodName: "GetSubs",
			Handler:    _SubscribesService_GetSubs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscribes/contract.proto",
}
