// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics/contract.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeSeriesInterval int32

const (
	TimeSeriesInterval_TIME_SERIES_INTERVAL_UNSPECIFIED TimeSeriesInterval = 0
	TimeSeriesInterval_TIME_SERIES_INTERVAL_HOUR        TimeSeriesInterval = 1
	TimeSeriesInterval_TIME_SERIES_INTERVAL_DAY         TimeSeriesInterval = 2
	TimeSeriesInterval_TIME_SERIES_INTERVAL_WEEK        TimeSeriesInterval = 3
)

// Enum value maps for TimeSeriesInterval.
var (
	TimeSeriesInterval_name = map[int32]string{
		0: "TIME_SERIES_INTERVAL_UNSPECIFIED",
		1: "TIME_SERIES_INTERVAL_HOUR",
		2: "TIME_SERIES_INTERVAL_DAY",
		3: "TIME_SERIES_INTERVAL_WEEK",
	}
	TimeSeriesInterval_value = map[string]int32{
		"TIME_SERIES_INTERVAL_UNSPECIFIED": 0,
		"TIME_SERIES_INTERVAL_HOUR":        1,
		"TIME_SERIES_INTERVAL_DAY":         2,
		"TIME_SERIES_INTERVAL_WEEK":        3,
	}
)

func (x TimeSeriesInterval) Enum() *TimeSeriesInterval {
	p := new(TimeSeriesInterval)
	*p = x
	return p
}

func (x TimeSeriesInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeSeriesInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_analytics_contract_proto_enumTypes[0].Descriptor()
}

func (TimeSeriesInterval) Type() protoreflect.EnumType {
	return &file_analytics_contract_proto_enumTypes[0]
}

func (x TimeSeriesInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeSeriesInterval.Descriptor instead.
func (TimeSeriesInterval) EnumDescriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{0}
}

type TrackEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventName      string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	AccountId      int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EntityType     string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId       int64                  `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,5,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	Properties     map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_analytics_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TrackEventRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TrackEventRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *TrackEventRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *TrackEventRequest) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

func (x *TrackEventRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_analytics_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUnix      int64                  `protobuf:"varint,1,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	ToUnix        int64                  `protobuf:"varint,2,opt,name=to_unix,json=toUnix,proto3" json:"to_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_analytics_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *GetMetricsRequest) GetToUnix() int64 {
	if x != nil {
		return x.ToUnix
	}
	return 0
}

type GetMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NewAccounts          int64                  `protobuf:"varint,1,opt,name=new_accounts,json=newAccounts,proto3" json:"new_accounts,omitempty"`
	Logins               int64                  `protobuf:"varint,2,opt,name=logins,proto3" json:"logins,omitempty"`
	ActiveAccounts       int64                  `protobuf:"varint,3,opt,name=active_accounts,json=activeAccounts,proto3" json:"active_accounts,omitempty"`
	SubscriptionsCreated int64                  `protobuf:"varint,4,opt,name=subscriptions_created,json=subscriptionsCreated,proto3" json:"subscriptions_created,omitempty"`
	SubscriptionsRemoved int64                  `protobuf:"varint,5,opt,name=subscriptions_removed,json=subscriptionsRemoved,proto3" json:"subscriptions_removed,omitempty"`
	RevenueMinor         int64                  `protobuf:"varint,6,opt,name=revenue_minor,json=revenueMinor,proto3" json:"revenue_minor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_analytics_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetNewAccounts() int64 {
	if x != nil {
		return x.NewAccounts
	}
	return 0
}

func (x *GetMetricsResponse) GetLogins() int64 {
	if x != nil {
		return x.Logins
	}
	return 0
}

func (x *GetMetricsResponse) GetActiveAccounts() int64 {
	if x != nil {
		return x.ActiveAccounts
	}
	return 0
}

func (x *GetMetricsResponse) GetSubscriptionsCreated() int64 {
	if x != nil {
		return x.SubscriptionsCreated
	}
	return 0
}

func (x *GetMetricsResponse) GetSubscriptionsRemoved() int64 {
	if x != nil {
		return x.SubscriptionsRemoved
	}
	return 0
}

func (x *GetMetricsResponse) GetRevenueMinor() int64 {
	if x != nil {
		return x.RevenueMinor
	}
	return 0
}

type TimeSeriesPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BucketStartUnix int64                  `protobuf:"varint,1,opt,name=bucket_start_unix,json=bucketStartUnix,proto3" json:"bucket_start_unix,omitempty"`
	Value           int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_analytics_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{4}
}

func (x *TimeSeriesPoint) GetBucketStartUnix() int64 {
	if x != nil {
		return x.BucketStartUnix
	}
	return 0
}

func (x *TimeSeriesPoint) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	FromUnix      int64                  `protobuf:"varint,2,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	ToUnix        int64                  `protobuf:"varint,3,opt,name=to_unix,json=toUnix,proto3" json:"to_unix,omitempty"`
	Interval      TimeSeriesInterval     `protobuf:"varint,4,opt,name=interval,proto3,enum=analytics.TimeSeriesInterval" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesRequest) Reset() {
	*x = GetTimeSeriesRequest{}
	mi := &file_analytics_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesRequest) ProtoMessage() {}

func (x *GetTimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimeSeriesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetTimeSeriesRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *GetTimeSeriesRequest) GetToUnix() int64 {
	if x != nil {
		return x.ToUnix
	}
	return 0
}

func (x *GetTimeSeriesRequest) GetInterval() TimeSeriesInterval {
	if x != nil {
		return x.Interval
	}
	return TimeSeriesInterval_TIME_SERIES_INTERVAL_UNSPECIFIED
}

type GetTimeSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesResponse) Reset() {
	*x = GetTimeSeriesResponse{}
	mi := &file_analytics_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesResponse) ProtoMessage() {}

func (x *GetTimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{6}
}

func (x *GetTimeSeriesResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetTopEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	FromUnix      int64                  `protobuf:"varint,3,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	ToUnix        int64                  `protobuf:"varint,4,opt,name=to_unix,json=toUnix,proto3" json:"to_unix,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopEntitiesRequest) Reset() {
	*x = GetTopEntitiesRequest{}
	mi := &file_analytics_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopEntitiesRequest) ProtoMessage() {}

func (x *GetTopEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopEntitiesRequest.ProtoReflect.Descriptor instead.
func (*GetTopEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopEntitiesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetTopEntitiesRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *GetTopEntitiesRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *GetTopEntitiesRequest) GetToUnix() int64 {
	if x != nil {
		return x.ToUnix
	}
	return 0
}

func (x *GetTopEntitiesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopEntity) Reset() {
	*x = TopEntity{}
	mi := &file_analytics_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopEntity) ProtoMessage() {}

func (x *TopEntity) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopEntity.ProtoReflect.Descriptor instead.
func (*TopEntity) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{8}
}

func (x *TopEntity) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *TopEntity) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTopEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopEntity           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopEntitiesResponse) Reset() {
	*x = GetTopEntitiesResponse{}
	mi := &file_analytics_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopEntitiesResponse) ProtoMessage() {}

func (x *GetTopEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopEntitiesResponse.ProtoReflect.Descriptor instead.
func (*GetTopEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{9}
}

func (x *GetTopEntitiesResponse) GetItems() []*TopEntity {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_analytics_contract_proto protoreflect.FileDescriptor

const file_analytics_contract_proto_rawDesc = "" +
	"\n" +
	"\x18analytics/contract.proto\x12\tanalytics\"\xc6\x02\n" +
	"\x11TrackEventRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\x03R\bentityId\x12(\n" +
	"\x10occurred_at_unix\x18\x05 \x01(\x03R\x0eoccurredAtUnix\x12L\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2,.analytics.TrackEventRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12TrackEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x11GetMetricsRequest\x12\x1b\n" +
	"\tfrom_unix\x18\x01 \x01(\x03R\bfromUnix\x12\x17\n" +
	"\ato_unix\x18\x02 \x01(\x03R\x06toUnix\"\x87\x02\n" +
	"\x12GetMetricsResponse\x12!\n" +
	"\fnew_accounts\x18\x01 \x01(\x03R\vnewAccounts\x12\x16\n" +
	"\x06logins\x18\x02 \x01(\x03R\x06logins\x12'\n" +
	"\x0factive_accounts\x18\x03 \x01(\x03R\x0eactiveAccounts\x123\n" +
	"\x15subscriptions_created\x18\x04 \x01(\x03R\x14subscriptionsCreated\x123\n" +
	"\x15subscriptions_removed\x18\x05 \x01(\x03R\x14subscriptionsRemoved\x12#\n" +
	"\rrevenue_minor\x18\x06 \x01(\x03R\frevenueMinor\"S\n" +
	"\x0fTimeSeriesPoint\x12*\n" +
	"\x11bucket_start_unix\x18\x01 \x01(\x03R\x0fbucketStartUnix\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\x9f\x01\n" +
	"\x14GetTimeSeriesRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1b\n" +
	"\tfrom_unix\x18\x02 \x01(\x03R\bfromUnix\x12\x17\n" +
	"\ato_unix\x18\x03 \x01(\x03R\x06toUnix\x129\n" +
	"\binterval\x18\x04 \x01(\x0e2\x1d.analytics.TimeSeriesIntervalR\binterval\"K\n" +
	"\x15GetTimeSeriesResponse\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.analytics.TimeSeriesPointR\x06points\"\x9c\x01\n" +
	"\x15GetTopEntitiesRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tfrom_unix\x18\x03 \x01(\x03R\bfromUnix\x12\x17\n" +
	"\ato_unix\x18\x04 \x01(\x03R\x06toUnix\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\">\n" +
	"\tTopEntity\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"D\n" +
	"\x16GetTopEntitiesResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.analytics.TopEntityR\x05items*\x96\x01\n" +
	"\x12TimeSeriesInterval\x12$\n" +
	" TIME_SERIES_INTERVAL_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TIME_SERIES_INTERVAL_HOUR\x10\x01\x12\x1c\n" +
	"\x18TIME_SERIES_INTERVAL_DAY\x10\x02\x12\x1d\n" +
	"\x19TIME_SERIES_INTERVAL_WEEK\x10\x032\xd3\x02\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"TrackEvent\x12\x1c.analytics.TrackEventRequest\x1a\x1d.analytics.TrackEventResponse\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1c.analytics.GetMetricsRequest\x1a\x1d.analytics.GetMetricsResponse\x12R\n" +
	"\rGetTimeSeries\x12\x1f.analytics.GetTimeSeriesRequest\x1a .analytics.GetTimeSeriesResponse\x12U\n" +
	"\x0eGetTopEntities\x12 .analytics.GetTopEntitiesRequest\x1a!.analytics.GetTopEntitiesResponseB&Z$grpc/contracts/analytics;analyticspbb\x06proto3"

var (
	file_analytics_contract_proto_rawDescOnce sync.Once
	file_analytics_contract_proto_rawDescData []byte
)

func file_analytics_contract_proto_rawDescGZIP() []byte {
	file_analytics_contract_proto_rawDescOnce.Do(func() {
		file_analytics_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_contract_proto_rawDesc), len(file_analytics_contract_proto_rawDesc)))
	})
	return file_analytics_contract_proto_rawDescData
}

var file_analytics_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analytics_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_analytics_contract_proto_goTypes = []any{
	(TimeSeriesInterval)(0),        // 0: analytics.TimeSeriesInterval
	(*TrackEventRequest)(nil),      // 1: analytics.TrackEventRequest
	(*TrackEventResponse)(nil),     // 2: analytics.TrackEventResponse
	(*GetMetricsRequest)(nil),      // 3: analytics.GetMetricsRequest
	(*GetMetricsResponse)(nil),     // 4: analytics.GetMetricsResponse
	(*TimeSeriesPoint)(nil),        // 5: analytics.TimeSeriesPoint
	(*GetTimeSeriesRequest)(nil),   // 6: analytics.GetTimeSeriesRequest
	(*GetTimeSeriesResponse)(nil),  // 7: analytics.GetTimeSeriesResponse
	(*GetTopEntitiesRequest)(nil),  // 8: analytics.GetTopEntitiesRequest
	(*TopEntity)(nil),              // 9: analytics.TopEntity
	(*GetTopEntitiesResponse)(nil), // 10: analytics.GetTopEntitiesResponse
	nil,                            // 11: analytics.TrackEventRequest.PropertiesEntry
}
var file_analytics_contract_proto_depIdxs = []int32{
	11, // 0: analytics.TrackEventRequest.properties:type_name -> analytics.TrackEventRequest.PropertiesEntry
	0,  // 1: analytics.GetTimeSeriesRequest.interval:type_name -> analytics.TimeSeriesInterval
	5,  // 2: analytics.GetTimeSeriesResponse.points:type_name -> analytics.TimeSeriesPoint
	9,  // 3: analytics.GetTopEntitiesResponse.items:type_name -> analytics.TopEntity
	1,  // 4: analytics.AnalyticsService.TrackEvent:input_type -> analytics.TrackEventRequest
	3,  // 5: analytics.AnalyticsService.GetMetrics:input_type -> analytics.GetMetricsRequest
	6,  // 6: analytics.AnalyticsService.GetTimeSeries:input_type -> analytics.GetTimeSeriesRequest
	8,  // 7: analytics.AnalyticsService.GetTopEntities:input_type -> analytics.GetTopEntitiesRequest
	2,  // 8: analytics.AnalyticsService.TrackEvent:output_type -> analytics.TrackEventResponse
	4,  // 9: analytics.AnalyticsService.GetMetrics:output_type -> analytics.GetMetricsResponse
	7,  // 10: analytics.AnalyticsService.GetTimeSeries:output_type -> analytics.GetTimeSeriesResponse
	10, // 11: analytics.AnalyticsService.GetTopEntities:output_type -> analytics.GetTopEntitiesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_analytics_contract_proto_init() }
func file_analytics_contract_proto_init() {
	if File_analytics_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_contract_proto_rawDesc), len(file_analytics_contract_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_contract_proto_goTypes,
		DependencyIndexes: file_analytics_contract_proto_depIdxs,
		EnumInfos:         file_analytics_contract_proto_enumTypes,
		MessageInfos:      file_analytics_contract_proto_msgTypes,
	}.Build()
	File_analytics_contract_proto = out.File
	file_analytics_contract_proto_goTypes = nil
	file_analytics_contract_proto_depIdxs = nil
}
