// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics/contract.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_analytics_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{0}
}

func (x *TrackEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *TrackEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEventRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TrackEventRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TrackEventRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TrackEventRequest) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_analytics_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{1}
}

func (x *TrackEventResponse) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	FromUnix      int64                  `protobuf:"varint,3,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	ToUnix        int64                  `protobuf:"varint,4,opt,name=to_unix,json=toUnix,proto3" json:"to_unix,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_analytics_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventsRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GetEventsRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *GetEventsRequest) GetToUnix() int64 {
	if x != nil {
		return x.ToUnix
	}
	return 0
}

func (x *GetEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_analytics_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Event) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Event               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_analytics_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsResponse) GetItems() []*Event {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetEventsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUnix      int64                  `protobuf:"varint,1,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	ToUnix        int64                  `protobuf:"varint,2,opt,name=to_unix,json=toUnix,proto3" json:"to_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_analytics_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricsRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *GetMetricsRequest) GetToUnix() int64 {
	if x != nil {
		return x.ToUnix
	}
	return 0
}

type MetricItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricItem) Reset() {
	*x = MetricItem{}
	mi := &file_analytics_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricItem) ProtoMessage() {}

func (x *MetricItem) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricItem.ProtoReflect.Descriptor instead.
func (*MetricItem) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{6}
}

func (x *MetricItem) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MetricItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetMetricsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountsCreated      uint64                 `protobuf:"varint,1,opt,name=accounts_created,json=accountsCreated,proto3" json:"accounts_created,omitempty"`
	Logins               uint64                 `protobuf:"varint,2,opt,name=logins,proto3" json:"logins,omitempty"`
	Logouts              uint64                 `protobuf:"varint,3,opt,name=logouts,proto3" json:"logouts,omitempty"`
	Refreshes            uint64                 `protobuf:"varint,4,opt,name=refreshes,proto3" json:"refreshes,omitempty"`
	SubscriptionsCreated uint64                 `protobuf:"varint,5,opt,name=subscriptions_created,json=subscriptionsCreated,proto3" json:"subscriptions_created,omitempty"`
	SubscriptionsUpdated uint64                 `protobuf:"varint,6,opt,name=subscriptions_updated,json=subscriptionsUpdated,proto3" json:"subscriptions_updated,omitempty"`
	SubscriptionsRemoved uint64                 `protobuf:"varint,7,opt,name=subscriptions_removed,json=subscriptionsRemoved,proto3" json:"subscriptions_removed,omitempty"`
	TotalEvents          uint64                 `protobuf:"varint,8,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	ByEventType          []*MetricItem          `protobuf:"bytes,9,rep,name=by_event_type,json=byEventType,proto3" json:"by_event_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_analytics_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_contract_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsResponse) GetAccountsCreated() uint64 {
	if x != nil {
		return x.AccountsCreated
	}
	return 0
}

func (x *GetMetricsResponse) GetLogins() uint64 {
	if x != nil {
		return x.Logins
	}
	return 0
}

func (x *GetMetricsResponse) GetLogouts() uint64 {
	if x != nil {
		return x.Logouts
	}
	return 0
}

func (x *GetMetricsResponse) GetRefreshes() uint64 {
	if x != nil {
		return x.Refreshes
	}
	return 0
}

func (x *GetMetricsResponse) GetSubscriptionsCreated() uint64 {
	if x != nil {
		return x.SubscriptionsCreated
	}
	return 0
}

func (x *GetMetricsResponse) GetSubscriptionsUpdated() uint64 {
	if x != nil {
		return x.SubscriptionsUpdated
	}
	return 0
}

func (x *GetMetricsResponse) GetSubscriptionsRemoved() uint64 {
	if x != nil {
		return x.SubscriptionsRemoved
	}
	return 0
}

func (x *GetMetricsResponse) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetMetricsResponse) GetByEventType() []*MetricItem {
	if x != nil {
		return x.ByEventType
	}
	return nil
}

var File_analytics_contract_proto protoreflect.FileDescriptor

const file_analytics_contract_proto_rawDesc = "" +
	"\n" +
	"\x18analytics/contract.proto\x12\tanalytics\"\xcd\x01\n" +
	"\x11TrackEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\"/\n" +
	"\x12TrackEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\"\x9c\x01\n" +
	"\x10GetEventsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tfrom_unix\x18\x03 \x01(\x03R\bfromUnix\x12\x17\n" +
	"\ato_unix\x18\x04 \x01(\x03R\x06toUnix\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"\xc1\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\"Q\n" +
	"\x11GetEventsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.analytics.EventR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"I\n" +
	"\x11GetMetricsRequest\x12\x1b\n" +
	"\tfrom_unix\x18\x01 \x01(\x03R\bfromUnix\x12\x17\n" +
	"\ato_unix\x18\x02 \x01(\x03R\x06toUnix\"A\n" +
	"\n" +
	"MetricItem\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\x8c\x03\n" +
	"\x12GetMetricsResponse\x12)\n" +
	"\x10accounts_created\x18\x01 \x01(\x04R\x0faccountsCreated\x12\x16\n" +
	"\x06logins\x18\x02 \x01(\x04R\x06logins\x12\x18\n" +
	"\alogouts\x18\x03 \x01(\x04R\alogouts\x12\x1c\n" +
	"\trefreshes\x18\x04 \x01(\x04R\trefreshes\x123\n" +
	"\x15subscriptions_created\x18\x05 \x01(\x04R\x14subscriptionsCreated\x123\n" +
	"\x15subscriptions_updated\x18\x06 \x01(\x04R\x14subscriptionsUpdated\x123\n" +
	"\x15subscriptions_removed\x18\a \x01(\x04R\x14subscriptionsRemoved\x12!\n" +
	"\ftotal_events\x18\b \x01(\x04R\vtotalEvents\x129\n" +
	"\rby_event_type\x18\t \x03(\v2\x15.analytics.MetricItemR\vbyEventType2\xf0\x01\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"TrackEvent\x12\x1c.analytics.TrackEventRequest\x1a\x1d.analytics.TrackEventResponse\x12F\n" +
	"\tGetEvents\x12\x1b.analytics.GetEventsRequest\x1a\x1c.analytics.GetEventsResponse\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1c.analytics.GetMetricsRequest\x1a\x1d.analytics.GetMetricsResponseB&Z$grpc/contracts/analytics;analyticspbb\x06proto3"

var (
	file_analytics_contract_proto_rawDescOnce sync.Once
	file_analytics_contract_proto_rawDescData []byte
)

func file_analytics_contract_proto_rawDescGZIP() []byte {
	file_analytics_contract_proto_rawDescOnce.Do(func() {
		file_analytics_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_contract_proto_rawDesc), len(file_analytics_contract_proto_rawDesc)))
	})
	return file_analytics_contract_proto_rawDescData
}

var file_analytics_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_analytics_contract_proto_goTypes = []any{
	(*TrackEventRequest)(nil),  // 0: analytics.TrackEventRequest
	(*TrackEventResponse)(nil), // 1: analytics.TrackEventResponse
	(*GetEventsRequest)(nil),   // 2: analytics.GetEventsRequest
	(*Event)(nil),              // 3: analytics.Event
	(*GetEventsResponse)(nil),  // 4: analytics.GetEventsResponse
	(*GetMetricsRequest)(nil),  // 5: analytics.GetMetricsRequest
	(*MetricItem)(nil),         // 6: analytics.MetricItem
	(*GetMetricsResponse)(nil), // 7: analytics.GetMetricsResponse
}
var file_analytics_contract_proto_depIdxs = []int32{
	3, // 0: analytics.GetEventsResponse.items:type_name -> analytics.Event
	6, // 1: analytics.GetMetricsResponse.by_event_type:type_name -> analytics.MetricItem
	0, // 2: analytics.AnalyticsService.TrackEvent:input_type -> analytics.TrackEventRequest
	2, // 3: analytics.AnalyticsService.GetEvents:input_type -> analytics.GetEventsRequest
	5, // 4: analytics.AnalyticsService.GetMetrics:input_type -> analytics.GetMetricsRequest
	1, // 5: analytics.AnalyticsService.TrackEvent:output_type -> analytics.TrackEventResponse
	4, // 6: analytics.AnalyticsService.GetEvents:output_type -> analytics.GetEventsResponse
	7, // 7: analytics.AnalyticsService.GetMetrics:output_type -> analytics.GetMetricsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_contract_proto_init() }
func file_analytics_contract_proto_init() {
	if File_analytics_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_contract_proto_rawDesc), len(file_analytics_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_contract_proto_goTypes,
		DependencyIndexes: file_analytics_contract_proto_depIdxs,
		MessageInfos:      file_analytics_contract_proto_msgTypes,
	}.Build()
	File_analytics_contract_proto = out.File
	file_analytics_contract_proto_goTypes = nil
	file_analytics_contract_proto_depIdxs = nil
}
